-- SpaceCraft Galaxy Map Database Setup Script
-- Paste this script into the Supabase SQL Editor and click "Run".

-- 1. CLEANUP (Optional: Uncomment if you want to start fresh)
-- DROP TABLE IF EXISTS connections;
-- DROP TABLE IF EXISTS systems;
-- DROP TABLE IF EXISTS sectors;

-- 2. CREATE TABLE: sectors
CREATE TABLE IF NOT EXISTS sectors (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    index INT,
    level TEXT,
    color TEXT NOT NULL DEFAULT '#ffffff',
    system_count INT DEFAULT 0,
    polygon JSONB, -- Array of coordinates: [[x1, y1], [x2, y2], ...]
    centroid JSONB, -- Center coordinate: { "x": float, "y": float }
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 3. CREATE TABLE: systems (Star Systems)
CREATE TABLE IF NOT EXISTS systems (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    game_id TEXT,
    designation TEXT,
    star_type TEXT NOT NULL DEFAULT 'DefaultStar',
    star_color TEXT NOT NULL DEFAULT 'Yellow',
    index INT,
    sector_id TEXT REFERENCES sectors(id) ON DELETE SET NULL,
    color TEXT NOT NULL DEFAULT '#ffffff',
    x DOUBLE PRECISION NOT NULL,
    y DOUBLE PRECISION NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 4. CREATE TABLE: planets
CREATE TABLE IF NOT EXISTS planets (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    system_id TEXT NOT NULL REFERENCES systems(id) ON DELETE CASCADE,
    designation TEXT,
    resources TEXT[] DEFAULT '{}', -- Array of resource names: ['Iron', 'Copper']
    deposits TEXT[] DEFAULT '{}', -- Array of deposits: ['Deposit_Iron']
    stations JSONB DEFAULT '[]'::jsonb, -- Array of space stations
    bases JSONB DEFAULT '[]'::jsonb, -- Array of planetary bases
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 5. CREATE TABLE: connections (FTL Jump Lanes)
CREATE TABLE IF NOT EXISTS connections (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    from_system_id TEXT NOT NULL REFERENCES systems(id) ON DELETE CASCADE,
    to_system_id TEXT NOT NULL REFERENCES systems(id) ON DELETE CASCADE,
    cost INT NOT NULL DEFAULT 10,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    CONSTRAINT unique_connection UNIQUE (from_system_id, to_system_id)
);

-- 6. ENABLE ROW LEVEL SECURITY (RLS)
ALTER TABLE sectors ENABLE ROW LEVEL SECURITY;
ALTER TABLE systems ENABLE ROW LEVEL SECURITY;
ALTER TABLE planets ENABLE ROW LEVEL SECURITY;
ALTER TABLE connections ENABLE ROW LEVEL SECURITY;

-- 7. SET RLS POLICIES FOR sectors
-- Policy: Allow anyone (anonymous and authenticated) to read sectors
CREATE POLICY "Allow public read access to sectors"
ON sectors FOR SELECT
USING (true);

-- Policy: Allow only authenticated users to insert, update, or delete sectors
CREATE POLICY "Allow write access to authenticated users on sectors"
ON sectors FOR ALL
TO authenticated
USING (true)
WITH CHECK (true);


-- 8. SET RLS POLICIES FOR systems
-- Policy: Allow anyone to read systems
CREATE POLICY "Allow public read access to systems"
ON systems FOR SELECT
USING (true);

-- Policy: Allow only authenticated users to write systems
CREATE POLICY "Allow write access to authenticated users on systems"
ON systems FOR ALL
TO authenticated
USING (true)
WITH CHECK (true);


-- 9. SET RLS POLICIES FOR planets
-- Policy: Allow anyone to read planets
CREATE POLICY "Allow public read access to planets"
ON planets FOR SELECT
USING (true);

-- Policy: Allow only authenticated users to write planets
CREATE POLICY "Allow write access to authenticated users on planets"
ON planets FOR ALL
TO authenticated
USING (true)
WITH CHECK (true);


-- 10. SET RLS POLICIES FOR connections
-- Policy: Allow anyone to read connections
CREATE POLICY "Allow public read access to connections"
ON connections FOR SELECT
USING (true);

-- Policy: Allow only authenticated users to write connections
CREATE POLICY "Allow write access to authenticated users on connections"
ON connections FOR ALL
TO authenticated
USING (true)
WITH CHECK (true);


-- 11. CREATE TABLE: stations (Space Stations)
CREATE TABLE IF NOT EXISTS stations (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    system_id TEXT NOT NULL REFERENCES systems(id) ON DELETE CASCADE,
    owner TEXT NOT NULL DEFAULT 'Independent',
    facilities JSONB DEFAULT '[]'::jsonb, -- Array of facilities
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 12. ENABLE ROW LEVEL SECURITY & SET RLS POLICIES FOR stations
ALTER TABLE stations ENABLE ROW LEVEL SECURITY;

-- Policy: Allow anyone to read stations
CREATE POLICY "Allow public read access to stations"
ON stations FOR SELECT
USING (true);

-- Policy: Allow only authenticated users to write stations
CREATE POLICY "Allow write access to authenticated users on stations"
ON stations FOR ALL
TO authenticated
USING (true)
WITH CHECK (true);


-- 13. CREATE INDEXES FOR OPTIMAL SEARCHING
CREATE INDEX IF NOT EXISTS idx_systems_sector_id ON systems(sector_id);
CREATE INDEX IF NOT EXISTS idx_systems_coordinates ON systems(x, y);
CREATE INDEX IF NOT EXISTS idx_planets_system_id ON planets(system_id);
CREATE INDEX IF NOT EXISTS idx_connections_from_to ON connections(from_system_id, to_system_id);
CREATE INDEX IF NOT EXISTS idx_stations_system_id ON stations(system_id);


-- Migration/Upgrade support:
ALTER TABLE planets ADD COLUMN IF NOT EXISTS bases JSONB DEFAULT '[]'::jsonb;


